services:
  - type: web
    name: soundgraph
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: LASTFM_API_SECRET
        sync: false
      - key: LASTFM_USERNAME
        sync: false
      - key: BLUESKY_HANDLE
        sync: false
      - key: BLUESKY_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
